---
- name: Copy nginx.conf
  copy:
    src: ../roles/nginx/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    
- name: Ensure servise nginx is restarted
  service:
    name: nginx
    state: restarted    