---
- name: Copy nginx.conf
  copy:
    src: ./roles/nginx/files/nginx.conf
    dest: /etc/nginx/nginx.conf
    
- name: Ensure servise nginx is started
  service:
    name: nginx
    state: started    