---
- name: Ensure Python 3.6 package is present
  apt:
    name: Python:3.6
    state: present

- name: Ensure git is present
  apt:
    name: git
    state: present

- name: Ensure pip package is present
  apt:
    name: python-pip
    state: present

- name: Ensure libs is present
  pip:
    requirements: /home/test_work/requirements.txt