- name: Start migrate database
  shell: flask db upgrade
  args:
    chdir: /home/test_work
  
- name: Ensure service test_work is present
  copy:
    src: "{{ src_folder }}"
    dest: "{{ dest_folder }}"

- name: Ensure test_work service is started
  service:
    name: test_work.service
    state: started
    enabled: yes