---
- name: Server configuration and start app
  hosts: all
  become: yes

  environment:
    FLASK_APP: app.py
    POSTGRESQL_URL: "postgresql://dbuser:fgL9g5Dm@127.0.0.1/app"
  
  roles:
    - default_packages
    - nginx
    - app   

  vars_files:
    - ../environments/environment_dir/host_vars/app_vars.yml  